### ISSUE TITLE
Can't start locally on windows 10

### ISSUE THREAD

**Issue by tigrazone** [gkjohnson/three-gpu-pathtracer#465]
npm start

> three-gpu-pathtracer@0.0.16 start
> cd example && parcel serve ./*.html --dist-dir ./dev-bundle/ --no-cache --no-hmr

Error: No native build was found for platform=win32 arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.16.1
    loaded from: C:\msys64\home\user\from-git\three-gpu-pathtracer\node_modules\lmdb

    at load.path (C:\msys64\home\user\from-git\three-gpu-pathtracer\node_modules\node-gyp-build\index.js:59:9)
    at load (C:\msys64\home\user\from-git\three-gpu-pathtracer\node_modules\node-gyp-build\index.js:21:30)
    at Object.<anonymous> (C:\msys64\home\user\from-git\three-gpu-pathtracer\node_modules\lmdb\dist\index.cjs:2257:47)
    at Module._compile (C:\msys64\home\user\from-git\three-gpu-pathtracer\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (C:\msys64\home\user\from-git\three-gpu-pathtracer\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at _lmdb (C:\msys64\home\user\from-git\three-gpu-pathtracer\node_modules\@parcel\cache\lib\LMDBCache.js:51:39)

**Comment by gkjohnson** [comment]
This is not a problem with this project - it's a problem with one of the dependencies. I'd report this to parcel or whatever seems to be causing the issue from the trace.

**Comment by tigrazone** [comment]
thank you.
remove node_modules and package-lock.json helps
